name: THE3 CI

on: [push]

jobs:
  build:
    name: build THE3
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make

    - name: run
      run: ./the3