name: MAKING CI

on: [push]

jobs:
  build:
    name: 构建及运行 MAKING
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: 构建
      run: cmake -H. -Bbuild && cmake --build ./build

    - name: 运行BINGO
      run: |
        TZ='Asia/Shanghai'; export TZ
        date +'%F %T %::z'
        # ./build/src/cicd/cicd
        ./build/src/bingo/bingo
    - name: 运行ShiAN
      run: |
        TZ='Asia/Shanghai'; export TZ
        date +'%F %T %::z'
        ./build/src/shian/ShiAN -name:"浦江一小 一(1)班 张芮安" -count:"40" -operation:"3" -limit:"20" -magic:"1"
