name: MAKING CI

on: [push]

jobs:
  build:
    name: 构建及运行 MAKING
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: 构建
      run: cmake -H. -Bbuild && cmake --build ./build

    - name: 运行
      run: |
        TZ='Asia/Shanghai'; export TZ
        date +'%F %T %::z'
        ./build/making
