name: THE3 CI

on: [push]

jobs:
  build:
    name: build and run THE3
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: make

    - name: run
      run: |
        echo '放胆开怀 尽情肆意'
        TZ='Asia/Shanghai'; export TZ
        date +'%F %T %::z'
        ./the3